### PR TITLE
Added grpc plugin to the OS X bundle.

### PR DESCRIPTION
**Pull request by dotbg**

### CODE REVIEW

**Comment by warmuuh** [comment]
thanks. i deliberately let GRPC plugin out of the appbundle as it is quite big (20 MB) and might not be used by many people. so do you think this is really necessary? you can still install the plugin manually by downloading the plugin archive and extract it into the existing milkman distribution (/plugin folder). for app-bundle, this means something like `/Applications/Milkman.app/Contents/Resources/plugins/`

**Comment by dotbg** [comment]
Hi Peter, the documentation says, 

> To install, run brew cask install milkman. All plugins are included.

I do not mind having it separately, but it would be handy to have the plugins published in the homebrew as well so that the docs for the OS X would match the instructions for the chocolatey.

Personally, I did the switch from postman to milkman because of the grpc plugin (at least, that's how I found milkman :) )

If you need any help on the packaging, feel free to contact me.

**Comment by warmuuh** [comment]
> If you need any help on the packaging, feel free to contact me.

actually, that would be nice cause i have no clue about homebrew... some other people set this up ;)
is this possible to be setup for e.g. grpc, so that it adds the grpc plugin to an existing milkman installation?
i then have to think about how to split it so that homebrew cask upgrade does not remove existing plugins

**Comment by warmuuh** [comment]
already included by now

**Pull request closed without merging**
